version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3079:3079'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
    env_file:
      - .env # Add environment variables from .env file
    command: npm run start:dev # Consider adding a dev script to package.json
    restart: unless-stopped
    init: true # Proper init process handling
    stdin_open: true # Improve interaction with the container
    tty: true # Improve terminal output
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
